### ISSUE TITLE
Minor updates in recipe/meta.yaml

### ISSUE THREAD

**Issue by orbeckst** [conda-forge/mdanalysis-feedstock#12]
@kain88-de , I am not sure how I ought to be doing updates to the meta data (I can submit a PR but I really don't want to re-render, I just want the following edits done for the 0.17.1 release, so I am adding an issue as a reminder):

In [recipe/meta.yaml](https://github.com/conda-forge/mdanalysis-feedstock/blob/master/recipe/meta.yaml)
* change url to SSL URL: https://www.mdanalysis.org
* change "toolkit" to "library"

**Comment by ocefpaf** [comment]
Not sure what you mean, but you will need to re-render to get recipes metada changes in the feedstock README.

@orbeckst ou can rerender with https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-rerender, it is quite convenient.

**Comment by kain88-de** [comment]
I would like the metadata like the URL to update on the anaconda website. Would this be done by publishing a new version of the package?

**Comment by ocefpaf** [comment]
You mean in the channel info at [anaconda.org](https://anaconda.org/conda-forge/mdanalysis)? I believe so, but I never really tested it.
