### ISSUE TITLE
Add tidynamics to conda recipe

### ISSUE THREAD

**Issue by hmacdope** [conda-forge/mdanalysis-feedstock#23]
Issue:
Tidynamics >=1.0.0 needs to be added to feedstock for the new msd analysis module. Related [PR:2619](https://github.com/MDAnalysis/mdanalysis/pull/2619) 
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by kain88-de** [comment]
This can be done once the pr is merged and we release a new version.

**Comment by hmacdope** [comment]
Thanks!

**Comment by orbeckst** [comment]
done in PR #43
