### ISSUE TITLE
Add support for ppc64le and arm64

### ISSUE THREAD

**Issue by IAlibay** [conda-forge/mdanalysis-feedstock#33]
Now that we have preliminary support for both, we should aim to make them available via conda-forge. Possibly after we do the initial 2.0.0 build.

**Comment by IAlibay** [comment]
Note: linux aarch64, not M1!

**Comment by orbeckst** [comment]
@IAlibay which of these do we have now (we also have M1 since PR #44 ...). Please decide if we can close.

**Comment by IAlibay** [comment]
neither currently, there's a separate cf migrator for this, but I've lost access to both ppc64le and armv8 machines I used to test on :(

**Comment by IAlibay** [comment]
Done
