### ISSUE TITLE
package is installable on python 3

### ISSUE THREAD

**Issue by kain88-de** [conda-forge/mdanalysis-feedstock#4]
This package is currently python 2.7 only. But we got [reports](https://github.com/MDAnalysis/mdanalysis/issues/1446) now that the package is installable on python 3 installations of conda. My initial impression was that this should be impossible with conda.

@conda-forge/core

**Comment by hainm** [comment]
@kain88-de I got the same issue. Please add "python" as a requirement for "run" here:

https://github.com/conda-forge/mdanalysis-feedstock/blob/master/recipe/meta.yaml#L26

**Comment by hainm** [comment]
Without that, conda assumes this package is python-independent.

**Comment by kain88-de** [comment]
Adding won't solve your problem as long as the old packages are still on anaconda

**Comment by hainm** [comment]
Why not updating the build number?

```
build:
  number: 0 # -> 1
```

**Comment by hainm** [comment]
My reply above is meant to help solving your 1st post.

**Comment by kain88-de** [comment]
The old packages will not be removed and they will still show up as installable on conda. Increasing the build number doesn't change that either. As long as installlabe packages are available conda will show them.

**Comment by hainm** [comment]
Does conda-forge not allow your to rebuild and reupload?

**Comment by kain88-de** [comment]
Rebuild and reupload yes. I will also do that. But the old packages will still be available and be picked up by conda. Deleting them will be a hassle.  Especially since I would like to keep the old versions around.

**Comment by kain88-de** [comment]
old packages aren't installable anymore on python 3
